### ISSUE TITLE
您好，这个使用文档打不开？

### ISSUE THREAD

**Issue by LYZ10** [WayneGongCN/rss-mailer#3]
您可以更新一下吗，不知道怎么操作呢

**Comment by WayneGongCN** [comment]
抱歉回复太晚。

使用说明已经同步到了 [README.md ](https://github.com/WayneGongCN/rss-mailer/blob/main/README.md)

**Comment by WayneGongCN** [comment]
@LYZ10 抱歉回复太晚

使用文档已经更新到 [README.md](https://github.com/WayneGongCN/rss-mailer/blob/main/README.md)

**Comment by LYZ10** [comment]
您好，谢谢您的回复。
想请教一下您，方便出个具体操作教程吗？0基础的小白看得不是很明白。感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WayneGongCN/rss-mailer] 您好，这个使用文档打不开？ (Issue #3)




 
Closed #3.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
