### ISSUE TITLE
似乎无法解码编码为gbk的rss订阅，以及如果rss中有图片链接，会显示有问题

### ISSUE THREAD

**Issue by davidelectricfree** [WayneGongCN/rss-mailer#8]
似乎无法解码编码为gbk的rss订阅
如：https://bbs.pinggu.org/forum.php?mod=rss&fid=286&auth=0

以及如果rss中有图片链接，会显示有问题
如：https://keylol.com/forum.php?mod=rss&fid=161&auth=0

![图片](https://user-images.githubusercontent.com/36690822/142553388-cadc014d-2ee4-4c68-b20e-8c7640e984a9.png)

**Comment by WayneGongCN** [comment]
GBK 编码已支持 #10 ，配置方式详见 [config.example.js](https://github.com/WayneGongCN/rss-mailer/blob/main/config.example.js#L5)

图片内容短期内还没有计划支持，新开了一个 ISSUE #12 计划将来跟进

**Comment by davidelectricfree** [comment]
> GBK 编码已支持 #10 ，配置方式详见 [config.example.js](https://github.com/WayneGongCN/rss-mailer/blob/main/config.example.js#L5)
> 
> 图片内容短期内还没有计划支持，新开了一个 ISSUE #12 计划将来跟进

谢谢。
